Copyright **`(c)`** 2023 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free for personal or classroom use; see [`LICENSE.md`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

In [1]:
from random import random, choice, randint
from functools import reduce
from collections import namedtuple
from queue import PriorityQueue, SimpleQueue, LifoQueue
from copy import copy

import numpy as np

In [28]:
PROBLEM_SIZE = 5
NUM_SETS = 20
SETS = tuple(np.array([random() < 0.3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
State = namedtuple('State', ['taken', 'not_taken'])
SETS

(array([False,  True, False, False, False]),
 array([ True, False, False, False, False]),
 array([False, False,  True,  True,  True]),
 array([False, False, False, False, False]),
 array([ True, False, False, False,  True]),
 array([False, False,  True, False, False]),
 array([ True,  True, False, False, False]),
 array([False,  True, False,  True,  True]),
 array([False, False, False,  True, False]),
 array([False, False, False, False, False]),
 array([False,  True, False, False,  True]),
 array([False, False, False,  True, False]),
 array([ True, False, False, False, False]),
 array([False, False, False, False, False]),
 array([False,  True, False, False, False]),
 array([False, False, False, False, False]),
 array([ True, False,  True,  True, False]),
 array([False, False, False, False,  True]),
 array([False, False,  True, False, False]),
 array([False, False,  True, False, False]))

In [29]:
# fitness1: valid only tells if set is covered (True) or not (False)
def fitness1(state):
    cost = sum(state)
    valid = np.all(
        reduce(
            np.logical_or,
            [SETS[i] for i, t in enumerate(state) if t],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        )
    )
    return valid, -cost # -> boolen, -cost

def fitness2(state):
    cost = sum(state) # how many sets i used among all NUM_SETS sets
    valid = np.sum( # count how many values are covered, i.e. how many True position are covered with these sets
        reduce(
            np.logical_or,
            [SETS[i] for i, t in enumerate(state) if t],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        )
    )
    return valid, -cost

fitness = fitness2

In [30]:
# randomly change a single tile in a state
def tweak(state):
    new_state = copy(state)
    index = randint(0, PROBLEM_SIZE - 1)
    new_state[index] = not new_state[index]
    return new_state

In [31]:
current_state = [choice([False, False, False, False, False, False]) for _ in range(NUM_SETS)]
print(fitness(current_state))

for step in range(200):
    print(current_state)
    new_state = tweak(current_state)
    print(new_state)
    if fitness(new_state) >= fitness(current_state):
        current_state = new_state
        print(fitness(current_state))

(0, 0)
[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
[False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
(2, -1)
[False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
[True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
(3, -2)
[True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
[True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
[True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [32]:
current_state

[True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]