Copyright **`(c)`** 2023 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free for personal or classroom use; see [`LICENSE.md`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

In [1]:
from random import random, choice, randint
from functools import reduce
from collections import namedtuple
from queue import PriorityQueue, SimpleQueue, LifoQueue
from copy import copy

import numpy as np

In [4]:
PROBLEM_SIZE = 10
NUM_SETS = 10
SETS = tuple(np.array([random() < .3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
State = namedtuple('State', ['taken', 'not_taken'])
SETS

(array([False, False, False, False, False, False,  True, False, False,
         True]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([False, False,  True, False, False, False, False, False, False,
        False]),
 array([False,  True, False, False, False, False, False,  True,  True,
        False]),
 array([False, False,  True, False, False, False, False, False, False,
        False]),
 array([ True,  True, False, False,  True, False, False, False, False,
        False]),
 array([False, False, False, False,  True, False, False, False, False,
        False]),
 array([False, False, False,  True,  True, False,  True, False,  True,
        False]),
 array([False, False, False, False, False,  True, False,  True, False,
         True]),
 array([False,  True, False, False, False, False, False, False, False,
         True]))

In [2]:
def evaluate(state):
    return np.all(reduce(
        np.logical_or,
        [SETS[i] for i, t in enumerate(state) if t],
        np.array([False for _ in range(PROBLEM_SIZE)]),
    )), -sum(state)


def distance(state):
    return PROBLEM_SIZE - sum(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        ))

In [5]:
current_state = [choice([True, False]) for _ in range(PROBLEM_SIZE)]
print(current_state)
evaluate(current_state)

[False, False, True, True, False, True, True, False, False, True]


(False, -5)

In [6]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"

NameError: name 'goal_check' is not defined

In [8]:
current_state = [False for _ in range(PROBLEM_SIZE)]
current_state

[False, False, False, False, False, False, False, False, False, False]

In [7]:
def tweak(state):
    new_state = copy(state)
    index = randint(0, PROBLEM_SIZE-1)
    new_state[index] = not new_state[index]
    return new_state

In [9]:
current_state = [choice([True, False]) for _ in range(PROBLEM_SIZE)]
print(current_state, evaluate(current_state))

for step in range(100):
    new_state = tweak(current_state)
    if evaluate(new_state) >= evaluate(current_state):
        current_state = new_state
        print(current_state, evaluate(current_state))

[False, True, False, False, False, False, False, True, False, True] (False, -3)
[False, False, False, False, False, False, False, True, False, True] (False, -2)
[False, False, False, False, False, False, False, True, False, False] (False, -1)
[False, False, False, False, False, False, False, False, False, False] (False, 0)


In [ ]:
frontier = PriorityQueue()
# frontier = SimpleQueue()
state = State(set(), set(range(NUM_SETS)))
frontier.put((distance(state), state))

counter = 0
_, current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    print(current_state)
    for action in current_state[1]:
        new_state = State(
            current_state.taken ^ {action},
            current_state.not_taken ^ {action},
        )
        frontier.put((distance(new_state), new_state))
        print(f'taken: {new_state.taken}')
        print(f'Not taken: {new_state.not_taken}')
        print()
    _, current_state = frontier.get()

print(
    f"Solved in {counter:,} steps ({len(current_state.taken)} tiles)"
)

In [ ]:
print('SOLUTION:')
print()
for s in current_state.taken:
    print(f'{s}: {SETS[s]}')