Copyright **`(c)`** 2023 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free for personal or classroom use; see [`LICENSE.md`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

In [2]:
from random import random
from functools import reduce
from collections import namedtuple
from queue import PriorityQueue, SimpleQueue, LifoQueue

import numpy as np

In [4]:
PROBLEM_SIZE = 5
NUM_SETS = 10
SETS = tuple(np.array([random() < .3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
State = namedtuple('State', ['taken', 'not_taken'])
SETS

((array([ True, False,  True,  True, False]),
  array([ True, False, False, False,  True]),
  array([False,  True, False, False, False]),
  array([False, False, False,  True, False]),
  array([False, False,  True, False,  True]),
  array([False, False, False, False, False]),
  array([ True, False,  True, False,  True]),
  array([ True, False, False, False,  True]),
  array([ True,  True, False, False, False]),
  array([ True,  True, False, False, False])),
 __main__.State)

In [9]:
def goal_check(state):
    return np.all(reduce(
        np.logical_or,
        [SETS[i] for i in state.taken],
        np.array([False for _ in range(PROBLEM_SIZE)]),
    ))


def distance(state):
    return PROBLEM_SIZE - sum(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        ))

In [6]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"

In [20]:
frontier = PriorityQueue()
# frontier = SimpleQueue()
state = State(set(), set(range(NUM_SETS)))
frontier.put((distance(state), state))

counter = 0
_, current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    print(current_state)
    for action in current_state[1]:
        new_state = State(
            current_state.taken ^ {action},
            current_state.not_taken ^ {action},
        )
        frontier.put((distance(new_state), new_state))
        print(f'taken: {new_state.taken}')
        print(f'Not taken: {new_state.not_taken}')
        print()
    _, current_state = frontier.get()

print(
    f"Solved in {counter:,} steps ({len(current_state.taken)} tiles)"
)

State(taken=set(), not_taken={0, 1, 2, 3, 4, 5, 6, 7, 8, 9})
taken: {0}
Not taken: {1, 2, 3, 4, 5, 6, 7, 8, 9}

taken: {1}
Not taken: {0, 2, 3, 4, 5, 6, 7, 8, 9}

taken: {2}
Not taken: {0, 1, 3, 4, 5, 6, 7, 8, 9}

taken: {3}
Not taken: {0, 1, 2, 4, 5, 6, 7, 8, 9}

taken: {4}
Not taken: {0, 1, 2, 3, 5, 6, 7, 8, 9}

taken: {5}
Not taken: {0, 1, 2, 3, 4, 6, 7, 8, 9}

taken: {6}
Not taken: {0, 1, 2, 3, 4, 5, 7, 8, 9}

taken: {7}
Not taken: {0, 1, 2, 3, 4, 5, 6, 8, 9}

taken: {8}
Not taken: {0, 1, 2, 3, 4, 5, 6, 7, 9}

taken: {9}
Not taken: {0, 1, 2, 3, 4, 5, 6, 7, 8}

State(taken={0}, not_taken={1, 2, 3, 4, 5, 6, 7, 8, 9})
taken: {0, 1}
Not taken: {2, 3, 4, 5, 6, 7, 8, 9}

taken: {0, 2}
Not taken: {1, 3, 4, 5, 6, 7, 8, 9}

taken: {0, 3}
Not taken: {1, 2, 4, 5, 6, 7, 8, 9}

taken: {0, 4}
Not taken: {1, 2, 3, 5, 6, 7, 8, 9}

taken: {0, 5}
Not taken: {1, 2, 3, 4, 6, 7, 8, 9}

taken: {0, 6}
Not taken: {1, 2, 3, 4, 5, 7, 8, 9}

taken: {0, 7}
Not taken: {1, 2, 3, 4, 5, 6, 8, 9}

taken: {8, 0}
No

In [21]:
print('SOLUTION:')
print()
for s in current_state.taken:
    print(f'{s}: {SETS[s]}')

SOLUTION:

0: [ True False  True  True False]
1: [ True False False False  True]
2: [False  True False False False]
